export { default as HomePage } from './pages/HomePage';
export { default as CollectionPage } from './pages/CollectionPage';
export { default as ShoppingCart } from './pages/ShoppingCart';
export { default as OrdersPage } from './pages/OrdersPage';
export { default as Navgation } from './Navigation';
export { default as WatchInfoAndAddButton } from './WatchInfoAndAddButton';
export { default as Slider } from './Slider';
export { default as LoadingIndicator } from './LoadingIndicator';
export { default as ToOrdersButton } from './ToOrdersButton';
